name: ci
reportingTeam: fnd-dtss
description: Collection of utilities for use in CI @ Outreach
slack: dev-tooling-support
library: true
commands:
  - ghaccesstoken
circleAPIKey: ""
lintroller: platinum
releaseType: ""
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  commands:
    - ghaccesstoken
  dependencies:
    optional: []
    required: []
  description: Collection of utilities for use in CI @ Outreach
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: platinum
  opslevel:
    confluenceSpaceKey: ""
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: false
  releaseOptions:
    allowMajorVersions: null
    enablePrereleases: false
  reportingTeam: fnd-dtss
  service: false
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
  - name: github.com/getoutreach/stencil-opslevel
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: ""
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
